Repository promptfoo/promptfoo, pull requests merged in 2025-07, with the labels that each got.

#4731 chore: reset generated constants after build
  package.json
Labels: codex

#4723 feat(cli): support pdb tracing in 3rd party Python scripts
  site/docs/providers/python.md
  site/docs/usage/troubleshooting.md
  src/envars.ts
  src/python/pythonUtils.ts
  test/python/pythonUtils.test.ts
Labels: codex

#4807 chore(internals): remove python script result data type debug log
  src/python/pythonUtils.ts
  test/python/pythonUtils.test.ts
Labels: codex

#4941 docs: standardize CrewAI image filenames to kebab-case
  site/docs/guides/evaluate-crewai.md
  site/static/img/docs/crewai/additional-config.png
  site/static/img/docs/crewai/additional-details.png
  site/static/img/docs/crewai/core-app.png
  site/static/img/docs/crewai/custom-target.png
  site/static/img/docs/crewai/llm-risk.png
  site/static/img/docs/crewai/plugin-config.png
  site/static/img/docs/crewai/promptfoo-dashboard.png
  site/static/img/docs/crewai/promptfoo-eval-2.png
  site/static/img/docs/crewai/promptfoo-web.png
  site/static/img/docs/crewai/red-team-target.png
  site/static/img/docs/crewai/review-config.png
  site/static/img/docs/crewai/running-config.png
  site/static/img/docs/crewai/security.png
  site/static/img/docs/crewai/strategy-config.png
  site/static/img/docs/crewai/test-summary.png
  site/static/img/docs/crewai/usage-details.png
  site/static/img/docs/crewai/vulnerabilities.png
Labels: documentation

#4964 fix(internal): Fixes filtering by metric keys which contain dots
  src/models/eval.ts
Labels: bug

#4966 feat(webui): First-class support for zooming eval results table
  src/app/src/pages/eval/components/ResultsTable.test.tsx
  src/app/src/pages/eval/components/ResultsTable.tsx
  src/app/src/pages/eval/components/ResultsView.tsx
Labels: enhancement
