Repository promptfoo/promptfoo, pull requests merged in 2025-05, with the labels that each got.

#3768 fix(cli): improve progress bar visualization with thread grouping
  src/evaluator.ts
  test/evaluator.test.ts
Labels: sourcery

#3870 docs(redteam): improve documentation for strategies
  site/docs/_shared/data/strategies.ts
  site/docs/red-team/strategies/audio.md
  site/docs/red-team/strategies/base64.md
  site/docs/red-team/strategies/basic.md
  site/docs/red-team/strategies/best-of-n.md
  site/docs/red-team/strategies/citation.md
  site/docs/red-team/strategies/composite-jailbreaks.md
  site/docs/red-team/strategies/custom.md
  site/docs/red-team/strategies/gcg.md
  site/docs/red-team/strategies/goat.md
  site/docs/red-team/strategies/hex.md
  site/docs/red-team/strategies/homoglyph.md
  site/docs/red-team/strategies/image.md
  site/docs/red-team/strategies/index.md
  site/docs/red-team/strategies/iterative.md
  site/docs/red-team/strategies/leetspeak.md
  site/docs/red-team/strategies/likert.md
  site/docs/red-team/strategies/math-prompt.md
  site/docs/red-team/strategies/multi-turn.md
  site/docs/red-team/strategies/multilingual.md
  site/docs/red-team/strategies/other-encodings.md
  site/docs/red-team/strategies/pandamonium.md
  site/docs/red-team/strategies/prompt-injection.md
  site/docs/red-team/strategies/retry.md
  site/docs/red-team/strategies/rot13.md
  site/docs/red-team/strategies/tree.md
Labels: sourcery

#3931 feat(cli): Adds global `--verbose` option
  site/docs/usage/command-line.md
  src/main.ts
Labels: enhancement

#3762 fix(bedrock): ensure numeric conversion for token counts
  src/providers/bedrock.ts
  test/providers/bedrock.test.ts
Labels: sourcery

#4052 fix(providers): AI21 response validation
  src/providers/ai21.ts
Labels: codex

#4058 chore: Update prompt suffix help text
  src/commands/eval.ts
Labels: codex

#4063 docs: update CLI docs
  site/docs/usage/command-line.md
Labels: codex

#4059 fix(webui): evaluateOptions removal in YAML editor
  src/app/src/pages/eval-creator/components/YamlEditor.test.tsx
  src/app/src/stores/evalConfig.ts
Labels: codex

#4066 chore(providers): update default openai models for openai:chat alias
  src/providers/registry.ts
  test/providers.test.ts
Labels: codex

#4067 docs: standardize code block titles
  site/docs/configuration/expected-outputs/index.md
  site/docs/configuration/scenarios.md
  site/docs/getting-started.md
  site/docs/guides/choosing-best-gpt-model.md
  site/docs/guides/cohere-command-r-benchmark.md
  site/docs/guides/compare-llama2-vs-gpt.md
  site/docs/guides/dbrx-benchmark.md
  site/docs/guides/deepseek-benchmark.md
  site/docs/guides/evaluate-json.md
  site/docs/guides/evaluate-llm-temperature.md
  site/docs/guides/evaluate-rag.md
  site/docs/guides/evaluate-replicate-lifeboat.md
  site/docs/guides/gemini-vs-gpt.md
  site/docs/guides/gpt-3.5-vs-gpt-4.md
  site/docs/guides/gpt-4-vs-gpt-4o.md
  site/docs/guides/gpt-vs-o1.md
  site/docs/guides/llama2-uncensored-benchmark-ollama.md
  site/docs/guides/mistral-vs-llama.md
  site/docs/guides/mixtral-vs-gpt.md
  site/docs/guides/prevent-llm-hallucations.md
  site/docs/guides/qwen-benchmark.md
  site/docs/guides/testing-llm-chains.md
  site/docs/providers/adaline.md
  site/docs/providers/anthropic.md
  site/docs/providers/azure.md
  site/docs/providers/google.md
  site/docs/providers/localai.md
  site/docs/providers/ollama.md
Labels: codex

#4050 chore: Improve memory usage when sharing results
  src/commands/eval.ts
  src/evaluator.ts
  src/models/eval.ts
  src/share.ts
  test/commands/eval/redteamWarning.test.ts
  test/evaluator.test.ts
  test/share.test.ts
Labels: codex

#4087 chore: update Google Sheets fetch to use proxy helper
  src/googleSheets.ts
  test/googleSheets.test.ts
Labels: codex

#4090 chore: add vision grading example
  examples/claude-vs-gpt-image/README.md
  examples/claude-vs-gpt-image/prompt.js
  examples/claude-vs-gpt-image/prompt.py
  examples/claude-vs-gpt-image/promptfooconfig.yaml
  site/docs/configuration/expected-outputs/model-graded/index.md
  src/assertions/llmRubric.ts
  src/matchers.ts
  test/assertions/llmRubric.test.ts
  test/matchers.test.ts
Labels: codex

#4103 chore(providers): support templated URLs in http
  site/docs/providers/http.md
  src/providers/http.ts
  test/providers/http.test.ts
Labels: codex

#4102 docs: add enterprise disclaimer to self-hosting
  site/docs/usage/self-hosting.md
Labels: codex

#4054 feat: Server-side pagination, filtering and search for eval results table
  drizzle/0012_late_marten_broadcloak.sql
  drizzle/0013_previous_dormammu.sql
  drizzle/0014_lazy_captain_universe.sql
  drizzle/meta/0012_snapshot.json
  drizzle/meta/0013_snapshot.json
  drizzle/meta/0014_snapshot.json
  drizzle/meta/_journal.json
  src/app/src/pages/eval/components/CompareEvalMenuItem.tsx
  src/app/src/pages/eval/components/ConfigModal.tsx
  src/app/src/pages/eval/components/CustomMetrics.test.tsx
  src/app/src/pages/eval/components/CustomMetrics.tsx
  src/app/src/pages/eval/components/DownloadMenu.test.tsx
  src/app/src/pages/eval/components/DownloadMenu.tsx
  src/app/src/pages/eval/components/Eval.tsx
  src/app/src/pages/eval/components/MetricFilterSelector.tsx
  src/app/src/pages/eval/components/ResultsCharts.tsx
  src/app/src/pages/eval/components/ResultsTable.test.tsx
  src/app/src/pages/eval/components/ResultsTable.tsx
  src/app/src/pages/eval/components/ResultsView.test.tsx
  src/app/src/pages/eval/components/ResultsView.tsx
  src/app/src/pages/eval/components/store.ts
  src/database/tables.ts
  src/evaluator.ts
  src/models/eval.ts
  src/models/evalResult.ts
  src/server/routes/eval.ts
  src/types/index.ts
  src/util/convertEvalResultsToTable.ts
  src/util/exportToFile/getHeaderForTable.ts
  src/util/exportToFile/index.ts
  src/util/index.ts
  test/evaluator.test.ts
  test/factories/evalFactory.ts
  test/models/eval.test.ts
  test/util/exportToFile/index.test.ts
Labels: codex

#4132 chore(redteam): add harmful plugin preset to redteam setup ui
  src/app/src/pages/redteam/setup/components/Plugins.tsx
  src/redteam/constants.ts
  test/redteam/constants.test.ts
Labels: codex

#4130 feat(providers): Add xAI image provider
  examples/xai-images/README.md
  examples/xai-images/promptfooconfig.yaml
  site/docs/providers/xai.md
  src/envars.ts
  src/providers/registry.ts
  src/providers/xai-image.ts
  test/providers/xai-image.test.ts
Labels: codex

#4142 fix(prompts): splitting when PROMPTFOO_PROMPT_SEPARATOR is contained within a string with text files
  src/prompts/processors/text.ts
  test/prompts/processors/text.test.ts
Labels: codex

#4131 chore(redteam): add label strategyless plugins in redteam setup ui
  src/app/src/pages/redteam/setup/components/Plugins.tsx
  src/redteam/constants.ts
  test/redteam/constants.test.ts
Labels: codex

#4124 chore(redteam): improve style of redteam purpose field in webui
  src/app/src/pages/redteam/setup/components/Purpose.tsx
Labels: codex

#4123 chore(providers): add xai live search support
  examples/xai-images/README.md
  examples/xai/README.md
  examples/xai/prompt.yaml
  examples/xai/promptfooconfig.images.yaml
  examples/xai/promptfooconfig.search.yaml
  examples/xai/promptfooconfig.yaml
  site/docs/providers/xai.md
  src/providers/xai.ts
  test/providers/xai.test.ts
Labels: codex

#4146 feat(redteam): add camelCase strategy
  site/docs/_shared/data/strategies.ts
  site/docs/red-team/strategies/other-encodings.md
  site/static/config-schema.json
  src/app/src/pages/redteam/setup/components/strategies/utils.ts
  src/redteam/constants.ts
  src/redteam/strategies/index.ts
  src/redteam/strategies/otherEncodings.ts
  test/redteam/constants.test.ts
  test/redteam/strategies/index.test.ts
  test/redteam/strategies/otherEncodings.test.ts
  test/redteam/validators.test.ts
Labels: codex

#4169 docs(site): document missing redteam plugins
  site/docs/_shared/data/plugins.ts
Labels: codex

#4181 fix: isolate proxy vars in bedrock tests
  test/providers/bedrock/index.test.ts
Labels: codex

#4186 feat: add typed row interfaces for eval queries
  src/models/eval.ts
Labels: codex

#4183 chore: remove redundant test comments
  test/feedback.test.ts
  test/redteam/index.test.ts
  test/redteam/plugins/pluginId.test.ts
  test/site/markdown.test.ts
Labels: codex

#4121 chore(redteam): add ToxicChat dataset as redteam plugin
  site/docs/_shared/data/plugins.ts
  site/docs/red-team/plugins/toxic-chat.md
  site/docs/red-team/plugins/toxicchat.md
  site/static/config-schema.json
  src/redteam/constants.ts
  src/redteam/graders.ts
  src/redteam/plugins/index.ts
  src/redteam/plugins/toxicchat.ts
  test/redteam/constants.test.ts
  test/redteam/graders.test.ts
  test/redteam/plugins/toxicchat.test.ts
Labels: codex

#4184 test: re-enable sql assertion edge cases
  src/assertions/sql.ts
  test/assertions/sql.test.ts
  test/redteam/providers/iterativeTree.test.ts
Labels: codex
